version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
  exclusions:
    paths:
      - examples
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - staticcheck
          - unused
          - ineffassign
